[[update-deps]]
== Override Spring Boot Dependencies

When using Spring for Apache Kafka in a Spring Boot application, the Kafka dependency versions are determined by Spring Boot's dependency management.
If you wish to use a different version, you need to override all of the associated dependencies.
This is especially true when using the embedded Kafka broker in `spring-kafka-test`.

**maven**

====
[source, xml, subs="+attributes"]
----
<dependency>
    <groupId>org.springframework.kafka</groupId>
    <artifactId>spring-kafka</artifactId>
    <version>{project-version}</version>
</dependency>

<dependency>
    <groupId>org.springframework.kafka</groupId>
    <artifactId>spring-kafka-test</artifactId>
    <version>{project-version}</version>
    <scope>test</scope>
</dependency>

<dependency>
    <groupId>org.apache.kafka</groupId>
    <artifactId>kafka-clients</artifactId>
    <version>{kafka-version}</version>
</dependency>

<!-- optional - only needed when using kafka-streams -->
<dependency>
    <groupId>org.apache.kafka</groupId>
    <artifactId>kafka-streams</artifactId>
    <version>{kafka-version}</version>
</dependency>

<dependency>
    <groupId>org.apache.kafka</groupId>
    <artifactId>kafka-clients</artifactId>
    <version>{kafka-version}</version>
    <classifier>test</classifier>
    <scope>test</scope>
</dependency>

<dependency>
    <groupId>org.apache.kafka</groupId>
    <artifactId>kafka_2.12</artifactId>
    <version>{kafka-version}</version>
    <scope>test</scope>
</dependency>

<dependency>
    <groupId>org.apache.kafka</groupId>
    <artifactId>kafka_2.12</artifactId>
    <version>{kafka-version}</version>
    <classifier>test</classifier>
    <scope>test</scope>
</dependency>
----
====

**gradle**

====
[source, groovy, subs="+attributes"]
----
dependencies {

    implementation 'org.springframework.kafka:spring-kafka:{project-version}'

    implementation "org.apache.kafka:kafka-clients:$kafkaVersion"
    implementation "org.apache.kafka:kafka-streams:$kafkaVersion" // optional - only needed when using kafka-streams
    testImplementation 'org.springframework.kafka:spring-kafka-test:{project-version}'
    testImplementation "org.apache.kafka:kafka-clients:$kafkaVersion:test"
    testImplementation "org.apache.kafka:kafka_2.12:$kafkaVersion"
    testImplementation "org.apache.kafka:kafka_2.12:$kafkaVersion:test"

}
----
====

The test scope dependencies are only needed if you are using the embedded Kafka broker in tests.

[appendix]
== Jackson/Scala Incompatibility

When using the framework and its test embedded Kafka server with Jackson version 2.11.3 or later on the classpath, Jackson pulls in some incompatible scala jars transitively.
The dependency management of Spring Boot version 2.3.5 and later uses that version of Jackson.
To correct this problem, you must override those jar versions.

**maven**

====
[source, xml]
----
<dependency>
    <groupId>org.scala-lang</groupId>
    <artifactId>scala-library</artifactId>
    <version>2.12.11</version>
    <scope>test</scope>
</dependency>

<dependency>
    <groupId>org.scala-lang</groupId>
    <artifactId>scala-reflect</artifactId>
    <version>2.12.11</version>
    <scope>test</scope>
</dependency>
----
====

**gradle**

====
[source, groovy]
----
testImplementation "org.scala-lang:scala-library:2.12.11"
testImplementation "org.scala-lang:scala-reflect:2.12.11"
----
====

[appendix]
[[history]]
== Change History

include::./changes-since-1.0.adoc[]
