=== What's New in 2.9 Since 2.8

This section covers the changes made from version 2.8 to version 2.9.
For changes in earlier version, see <<history>>.

[[x29-kafka-client]]
==== Kafka Client Version

This version requires the 3.2.0 `kafka-clients`

[[x29-eh-changes]]
==== Error Handler Changes

The `DefaultErrorHandler` can now be configured to pause the container for one poll and use the remaining results from the previous poll, instead of seeking to the offsets of the remaining records.
See <<default-eh>> for more information.

The `DefaultErrorHandler` now has a `BackOffHandler` property.
See <<backoff-handlers>> for more information.

[[x29-lc-changes]]
==== Listener Container Changes

`interceptBeforeTx` now works with all transaction managers (previously it was only applied when a `KafkaAwareTransactionManager` was used).
See <<interceptBeforeTx>>.

A new container property `pauseImmediate` is provided which allows the container to pause the consumer after the current record is processed, instead of after all the records from the previous poll have been processed.
See <<pauseImmediate>>.

Events related to consumer authentication and authorization

[[x29-hm-changes]]
==== Header Mapper Changes

You can now configure which inbound headers should be mapped.
Also available in version 2.8.8 or later.
See <<headers>> for more information.

[[x29-template-changes]]
==== `KafkaTemplate` Changes

In 3.0, the futures returned by this class will be `CompletableFuture` s instead of `ListenableFuture` s.
See <<kafka-template>> for assistance in transitioning when using this release.

[[x29-rkt-changes]]
==== `ReplyingKafkaTemplate` Changes

The template now provides a method to wait for assignment on the reply container, to avoid a race when sending a request before the reply container is initialized.
Also available in version 2.8.8 or later.
See <<replying-template>>.

In 3.0, the futures returned by this class will be `CompletableFuture` s instead of `ListenableFuture` s.
See <<replying-template>> and <<exchanging-messages>> for assistance in transitioning when using this release.
