=== What's New in 2.8 Since 2.7

This section covers the changes made from version 2.7 to version 2.8.
For changes in earlier version, see <<history>>.

[[x28-kafka-client]]
==== Kafka Client Version

This version requires the 2.8.0 `kafka-clients`.

[[x28-ooo-commits]]
==== Out of Order Manual Commits

The listener container can now be configured to accept manual offset commits out of order (usually asynchronously).
The container will defer the commit until the missing offset is acknowledged.
See <<ooo-commits>> for more information.

[[x28-template]]
==== `KafkaTemplate` Changes

You can now receive a single record, given the topic, partition and offset.
See <<kafka-template-receive>> for more information.

[[x28-eh]]
==== `CommonErrorHandler` Added

The legacy `GenericErrorHandler` and its sub-interface hierarchies for record an batch listeners have been replaced by a new single interface `CommonErrorHandler` with implementations corresponding to most legacy implementations of `GenericErrorHandler`.
See <<error-handlers>> for more information.
