=== What's New in 3.0 Since 2.9

This section covers the changes made from version 2.9 to version 3.0.
For changes in earlier version, see <<history>>.

[[x30-kafka-client]]
==== Kafka Client Version

This version requires the 3.2.0 `kafka-clients`.

[[x30-eos]]
==== Exactly Once Semantics

`EOSMode.V1` (aka `ALPHA`) is no longer supported.

IMPORTANT: When using transactions, the minimum broker version is 2.5.

See <<exactly-once>> and https://cwiki.apache.org/confluence/display/KAFKA/KIP-447%3A+Producer+scalability+for+exactly+once+semantics[KIP-447] for more information.

[[x30-obs]]
==== Observation

Enabling observation for timers and tracing using Micrometer is now supported.
See <<observation>> for more information.

[[x30-global-embedded-kafka]]
==== Global Single Embedded Kafka

The embedded Kafka (`EmbeddedKafkaBroker`) can now be start as a single global instance for the whole test plan.
See <<same-broker-multiple-tests>> for more information.

[[x30-retryable]]
==== Retryable Topics Changes

The bootstrapping of <<retry-topic>> infrastructure beans has changed in this release to avoid some timing problems that occurred in some application regarding application initialization.
See <<retry-config>> for more information.

[[x30-lc-changes]]
==== Listener Container Changes

Events related to consumer authentication and authorization failures are now published by the container.
See <<events>> for more information.

[[x30-template-changes]]
==== `KafkaTemplate` Changes

The futures returned by this class are now `CompletableFuture` s instead of `ListenableFuture` s.
See <<kafka-template>>.

[[x30-rkt-changes]]
==== `ReplyingKafkaTemplate` Changes

The futures returned by this class are now `CompletableFuture` s instead of `ListenableFuture` s.
See <<replying-template>> and <<exchanging-messages>>.
